export const SERVERS = [
  {
    id: 1,
    type: 'xtream',
    name: 'DNS Smarters',
    url: 'http://esma26.top',
    priority: 1,
    active: true,
  },
  {
    id: 2,
    type: 'xtream',
    name: 'DNS XCIPTV 1',
    url: 'http://alerquinaz.top:80',
    priority: 2,
    active: true,
  },
  {
    id: 3,
    type: 'xtream',
    name: 'DNS XCIPTV 2',
    url: 'http://newxczs.top:80',
    priority: 3,
    active: true,
  },
  {
    id: 4,
    type: 'xtream',
    name: 'DNS XCIPTV 3',
    url: 'http://p2golld.top:80',
    priority: 4,
    active: true,
  },
  {
    id: 5,
    type: 'xtream',
    name: 'DNS XCIPTV 4',
    url: 'http://zed3.top:80',
    priority: 5,
    active: true,
  },
  {
    id: 6,
    type: 'xtream',
    name: 'DNS Alternativa 1',
    url: 'http://alerquinaz.top',
    priority: 6,
    active: true,
  },
  {
    id: 7,
    type: 'xtream',
    name: 'DNS Alternativa 2',
    url: 'http://p2golld.top',
    priority: 7,
    active: true,
  },
  {
    id: 8,
    type: 'xtream',
    name: 'DNS Alternativa 3',
    url: 'http://zed3.top',
    priority: 8,
    active: true,
  },
  {
    id: 9,
    type: 'xtream',
    name: 'DNS Parceiro',
    url: 'http://prbfeliz.top',
    priority: 9,
    active: true,
  },
]

export const FAILOVER_CONFIG = {
  timeoutMs: 8000,
  stallTimeoutMs: 1200,
  maxRetries: 2,
  retryDelayMs: 1000,
  autoSwitch: true,
  showNotification: true,
  autoReconnect: false,
}

export const APP_CONFIG = {
  appName: 'MSPlay',
  version: '1.0.0',
  defaultVolume: 0.8,
  cardsPerRow: 6,
  infiniteScrollStep: 20,
  proxyUrl: 'https://falling-water-aba0.theusraro.workers.dev',
}
